### ISSUE TITLE
Incorrect table name

### ISSUE THREAD

**Issue by stv8** [Swetarts/cs373-idb#47]
Shouldn't this table be `comic_issue` instead of `comic_series`?

https://github.com/stv8/cs373-idb/blame/master/models.py#L174

**Comment by tcorley** [comment]
I should be, but I was flaky about the table names in the UML. That should be changed if we want to keep the vernacular correct.

**Comment by stv8** [comment]
I'm wondering if that is why I was getting that error because @maxgax  just added this a few days ago right before I got the error.

https://github.com/stv8/cs373-idb/blame/master/models.py#L214
